# Generated by Django 4.0.1 on 2022-02-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'product'},
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
